Solution for task 1
The-Downtown-Club/Sept-Exercises pull request #3
Opened 2022-09-13 12:21 UTC by vijay0019

Pull request for solution of 1_shopify_domains

2022-09-17 07:38 UTC, fenilgandhi requested changes

2022-09-17 07:38 UTC, fenilgandhi commented on week_1_basics/1_shopify_domains/1_vijay.py
> +      print(found_msg + url)
We have to return the value, not print it

2022-09-17 07:38 UTC, fenilgandhi commented on week_1_basics/1_shopify_domains/1_vijay.py
> +  if schema[0] == 'http:' or schema[0] == 'https:':
This does not handle cases where website only supports https and domain has http

2022-09-24 06:20 UTC, vijay0019 commented
Task 2 solution

2023-04-06 07:52 UTC, closed without merging